version: '3'
networks:
  my_network:
    driver: bridge
  
services:
  mysql:
    image: mysql:latest
    container_name: DBserver
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=yuno
      - MYSQL_PASSWORD=1234
      - character-set-server=utf8mb4
      - collation-server=utf8mb4_unicode_ci
    networks:
      - my_network
  
